{
  "$schema": "https://developers.cloudflare.com/pages/functions/schema.json",
  "production": {
    "compatibility_date": "2024-01-01",
    "build": {
      "command": "npm run build",
      "cwd": "/",
      "watch_paths": ["src/**", "public/**", "index.html", "package.json"]
    },
    "deployment": {
      "environment_variables": {
        "NODE_VERSION": "18"
      }
    }
  },
  "preview": {
    "compatibility_date": "2024-01-01",
    "build": {
      "command": "npm run build",
      "cwd": "/"
    }
  }
}
